import 'package:flutter/material.dart';
import 'package:budgett_frontend/presentation/utils/currency_formatter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:budgett_frontend/presentation/providers/finance_provider.dart';
import 'package:budgett_frontend/data/models/goal_model.dart';
import 'package:budgett_frontend/presentation/widgets/common/dialog_header.dart';
import 'package:budgett_frontend/presentation/widgets/common/dialog_constants.dart';
import 'package:budgett_frontend/presentation/widgets/common/icon_picker_grid.dart';
import 'package:budgett_frontend/presentation/widgets/common/currency_form_field.dart';
import 'package:budgett_frontend/presentation/widgets/common/date_picker_field.dart';

class AddGoalDialog extends ConsumerStatefulWidget {
  const AddGoalDialog({super.key});

  @override
  ConsumerState<AddGoalDialog> createState() => _AddGoalDialogState();
}

class _AddGoalDialogState extends ConsumerState<AddGoalDialog> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _targetAmountController = TextEditingController();
  final _currentAmountController = TextEditingController();

  DateTime? _selectedDeadline;
  String _selectedIcon = 'flag';

  @override
  void dispose() {
    _nameController.dispose();
    _targetAmountController.dispose();
    _currentAmountController.dispose();
    super.dispose();
  }

  Future<void> _saveGoal() async {
    if (!_formKey.currentState!.validate()) return;

    final goal = Goal(
      id: '', // Will be generated by DB
      name: _nameController.text,
      targetAmount: CurrencyFormatter.parse(_targetAmountController.text),
      currentAmount: _currentAmountController.text.isEmpty
          ? 0.0
          : CurrencyFormatter.parse(_currentAmountController.text),
      deadline: _selectedDeadline,
      iconName: _selectedIcon,
      createdAt: DateTime.now(),
    );

    try {
      await ref.read(financeRepositoryProvider).addGoal(goal);

      // Invalidate to refresh
      ref.invalidate(goalsProvider);

      if (mounted) {
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Goal created successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final daysToDeadline = _selectedDeadline != null
        ? _selectedDeadline!.difference(DateTime.now()).inDays
        : 0;

    final monthsToDeadline = (daysToDeadline / 30).ceil();
    final effectiveMonths = monthsToDeadline <= 0 ? 1 : monthsToDeadline;

    final targetAmount = CurrencyFormatter.parse(_targetAmountController.text);

    final monthlySavings = targetAmount / effectiveMonths;

    return Dialog(
      child: Container(
        constraints: const BoxConstraints(maxWidth: 500, maxHeight: 700),
        padding: const EdgeInsets.all(24),
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const DialogHeader(title: 'Add Financial Goal'),
                const SizedBox(height: 24),

                // Icon Selector
                Text('Icon', style: Theme.of(context).textTheme.titleSmall),
                const SizedBox(height: 8),
                IconPickerGrid(
                  iconOptions: kGoalIconOptions,
                  selectedIcon: _selectedIcon,
                  onIconSelected: (k) => setState(() => _selectedIcon = k),
                ),
                const SizedBox(height: 16),

                // Name
                TextFormField(
                  controller: _nameController,
                  decoration: const InputDecoration(
                    labelText: 'Goal Name',
                    border: OutlineInputBorder(),
                    hintText: 'e.g., Buy a car, Emergency fund',
                  ),
                  validator: (value) => value?.isEmpty ?? true ? 'Required' : null,
                ),
                const SizedBox(height: 16),

                // Target Amount
                CurrencyFormField(
                  controller: _targetAmountController,
                  labelText: 'Target Amount',
                  onChanged: (_) => setState(() {}),
                ),
                const SizedBox(height: 16),

                // Current Amount
                TextFormField(
                  controller: _currentAmountController,
                  decoration: const InputDecoration(
                    labelText: 'Current Amount (optional)',
                    prefixText: '\$',
                    border: OutlineInputBorder(),
                    hintText: '0',
                  ),
                  keyboardType: const TextInputType.numberWithOptions(decimal: true),
                  inputFormatters: [CurrencyInputFormatter()],
                ),
                const SizedBox(height: 16),

                // Deadline
                DatePickerField(
                  selectedDate: _selectedDeadline,
                  label: 'Deadline (optional)',
                  firstDate: DateTime.now(),
                  lastDate: DateTime.now().add(const Duration(days: 3650)),
                  onDateSelected: (d) => setState(() => _selectedDeadline = d),
                ),
                const SizedBox(height: 16),

                // Monthly Savings Calculator
                if (_selectedDeadline != null && targetAmount > 0)
                  SizedBox(
                    width: double.infinity,
                    child: Card(
                      color: Theme.of(context).colorScheme.primaryContainer,
                      child: Padding(
                        padding: const EdgeInsets.all(12),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Recommended Monthly Savings',
                              style: Theme.of(context).textTheme.titleSmall,
                            ),
                            const SizedBox(height: 4),
                            Text(
                              '${CurrencyFormatter.format(monthlySavings, decimalDigits: 2)} / month',
                              style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                                fontWeight: FontWeight.bold,
                                color: Theme.of(context).colorScheme.onPrimaryContainer,
                              ),
                            ),
                            Text(
                              'for $monthsToDeadline months',
                              style: Theme.of(context).textTheme.bodySmall,
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                const SizedBox(height: 24),

                // Save Button
                SizedBox(
                  width: double.infinity,
                  child: FilledButton(
                    onPressed: _saveGoal,
                    child: const Padding(
                      padding: EdgeInsets.all(16.0),
                      child: Text('Create Goal'),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
