import 'package:flutter/material.dart';
import 'package:budgett_frontend/presentation/utils/currency_formatter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:budgett_frontend/presentation/providers/finance_provider.dart';
import 'package:budgett_frontend/data/models/budget_model.dart';

class EditBudgetDialog extends ConsumerStatefulWidget {
  final String categoryId;
  final String categoryName;
  final int month;
  final int year;
  final double? currentAmount;

  const EditBudgetDialog({
    super.key,
    required this.categoryId,
    required this.categoryName,
    required this.month,
    required this.year,
    this.currentAmount,
  });

  @override
  ConsumerState<EditBudgetDialog> createState() => _EditBudgetDialogState();
}

class _EditBudgetDialogState extends ConsumerState<EditBudgetDialog> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _amountController;

  @override
  void initState() {
    super.initState();
    _amountController = TextEditingController(
      text: widget.currentAmount != null 
        ? CurrencyFormatter.format(widget.currentAmount!, includeSymbol: false) 
        : '',
    );
  }

  @override
  void dispose() {
    _amountController.dispose();
    super.dispose();
  }

  Future<void> _saveBudget() async {
    if (!_formKey.currentState!.validate()) return;

    final budget = Budget(
      id: '', // Will be generated by DB
      categoryId: widget.categoryId,
      amount: CurrencyFormatter.parse(_amountController.text),
      month: widget.month,
      year: widget.year,
    );

    try {
      await ref.read(financeRepositoryProvider).setBudget(budget);
      
      // Invalidate to refresh
      ref.invalidate(budgetsProvider);
      
      if (mounted) {
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Budget updated successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text('Set Budget for ${widget.categoryName}'),
      content: Form(
        key: _formKey,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextFormField(
              controller: _amountController,
              decoration: const InputDecoration(
                labelText: 'Budget Amount',
                prefixText: '\$',
                border: OutlineInputBorder(),
              ),
              keyboardType: const TextInputType.numberWithOptions(decimal: true),
              inputFormatters: [CurrencyInputFormatter()],
              autofocus: true,
              validator: (value) {
                if (value == null || value.isEmpty) return 'Required';
                if (CurrencyFormatter.parse(value) == 0.0 && value != '0' && value != '0.0') return 'Invalid number';
                return null;
              },
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        FilledButton(
          onPressed: _saveBudget,
          child: const Text('Save'),
        ),
      ],
    );
  }
}
