import 'package:flutter/material.dart';
import 'package:budgett_frontend/presentation/utils/currency_formatter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:budgett_frontend/presentation/providers/finance_provider.dart';
import 'package:budgett_frontend/data/models/budget_model.dart';
import 'package:budgett_frontend/presentation/utils/icon_helper.dart';
import 'package:budgett_frontend/presentation/widgets/common/currency_form_field.dart';

class EditBudgetDialog extends ConsumerStatefulWidget {
  final String categoryId;
  final String categoryName;
  final int month;
  final int year;
  final double? currentAmount;
  final String? categoryType;
  final String? categoryIcon;
  final String? categoryColor;

  const EditBudgetDialog({
    super.key,
    required this.categoryId,
    required this.categoryName,
    required this.month,
    required this.year,
    this.currentAmount,
    this.categoryType,
    this.categoryIcon,
    this.categoryColor,
  });

  @override
  ConsumerState<EditBudgetDialog> createState() => _EditBudgetDialogState();
}

class _EditBudgetDialogState extends ConsumerState<EditBudgetDialog> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _amountController;

  @override
  void initState() {
    super.initState();
    _amountController = TextEditingController(
      text: widget.currentAmount != null
        ? CurrencyFormatter.format(widget.currentAmount!, includeSymbol: false)
        : '',
    );
  }

  @override
  void dispose() {
    _amountController.dispose();
    super.dispose();
  }

  Future<void> _saveBudget() async {
    if (!_formKey.currentState!.validate()) return;

    final budget = Budget(
      id: '', // Will be generated by DB
      categoryId: widget.categoryId,
      amount: CurrencyFormatter.parse(_amountController.text),
      month: widget.month,
      year: widget.year,
    );

    try {
      await ref.read(financeRepositoryProvider).setBudget(budget);

      // Invalidate to refresh
      ref.invalidate(budgetsProvider);

      if (mounted) {
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Budget updated successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isIncome = widget.categoryType == 'income';
    final color = widget.categoryColor != null
        ? Color(int.parse(widget.categoryColor!))
        : Colors.grey;

    return AlertDialog(
      title: Row(
        children: [
          if (widget.categoryIcon != null)
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: color.withOpacity(0.2),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Icon(
                IconHelper.getIcon(widget.categoryIcon!),
                color: color,
                size: 24,
              ),
            ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  widget.categoryName,
                  style: Theme.of(context).textTheme.titleLarge,
                ),
                const SizedBox(height: 4),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                  decoration: BoxDecoration(
                    color: isIncome ? Colors.green.withOpacity(0.2) : Colors.orange.withOpacity(0.2),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    isIncome ? 'Income' : 'Expense',
                    style: TextStyle(
                      fontSize: 12,
                      color: isIncome ? Colors.green : Colors.orange,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
      content: Form(
        key: _formKey,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            CurrencyFormField(
              controller: _amountController,
              labelText: isIncome ? 'Expected Income' : 'Budget Amount',
              autofocus: true,
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        FilledButton(
          onPressed: _saveBudget,
          child: const Text('Save'),
        ),
      ],
    );
  }
}
